name: $(Build.BuildID)

trigger:
  batch: true
  branches:
    include:
      - topic/*

pr:
  - master

variables:
- group: 'SonarQube as a Service'

- name: HostingPlan
  value: 'asp-SqHosting$(SuffixName)'
- name: SqlDb
  value: 'sqldb-sqhosting$(SuffixName)'
- name: SqlServer
  value: 'sqlsrv-sqhosting$(SuffixName)'
- name: Website
  value: 'wa-SqHosting$(SuffixName)'
- name: KeyVault
  value: 'kv-sqsecrets$(SuffixName)'
- name: ResourceGroup
  value: 'Rp-SonarQubeAsAService'
- name: ResourceGroupKeyVault
  value: 'RG-GlobalKeyVault'  
- name: SkuCapacity
  value: '1'
- name: SkuSize
  value: 'S1'

# creates a counter based on the suffix name to make sure resources are unique. 
# This is not 100% safe though.
- name: TestRun
  value: $[counter(variables['SuffixName'], 0)]

stages:

### BUILD STAGE ###
###################

- stage: Build
  displayName: Build Stage
  jobs:

  ### Check ARM Templates ###

  - job: Build_ARM_Phase
    displayName: 'Build ARM'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Validate ARM Templates'
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: '$(AzureConnectionServiceName)'
        subscriptionName: '$(SubscriptionGuid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(ResourceGroup)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'ARM/sonar.azuredeploy.json'
        csmParametersFile: 'ARM/sonar.azuredeploy.parameters.json'
        overrideParameters: '-hostingPlanName "$(HostingPlan)" -webSiteName "$(Website)" -sqlserverName "$(SqlServer)" -databaseName "$(SqlDb)" -skuName "$(SkuSize)" -skuCapacity $(SkuCapacity) -sqlAdministratorLogin "$(SqlAdmin)" -sqlAdministratorLoginPassword "$(SqlAdminPassword)"'
        deploymentMode: 'Validation'

    - task: CopyFiles@2
      displayName: 'Copy ARM Files to: AzureRessources Folder'
      inputs:
        SourceFolder: ARM
        TargetFolder: '$(build.artifactstagingdirectory)/AzureRessources'

    - publish: $(build.artifactstagingdirectory)/AzureRessources
      displayName: 'Publish ARM Files'
      artifact:  AzureRessources
    - task: CopyFiles@2
      displayName: 'Copy Deploy and Run Scripts'
      inputs:
        Contents: |
          Deploy/**/*.ps1
          Run/**/*.ps1
          **/sonar.properties
          **/*.config
        TargetFolder: '$(build.artifactstagingdirectory)/InstallScripts'
      
    - publish: $(build.artifactstagingdirectory)/InstallScripts
      displayName: 'Publish Deploy and Run Scripts'
      artifact:  InstallScripts

  ### Real Test Deployment of Infrastructure ###
  - deployment: Test_ARM_Deployment_Phase
    displayName: 'Test ARM Deployment'
    dependsOn: 'Build_ARM_Phase'
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test ARM Deployment
    strategy:
       runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download AzureRessources
            artifact: AzureRessources
            patterns: '**/*.json'
          - template: Pipeline/deployArm.yml
            parameters:
              AzureConnectionServiceName: '$(AzureConnectionServiceName)'
              SubscriptionGuid: '$(SubscriptionGuid)'
              KeyVaultResourceGroup: '$(ResourceGroupKeyVault)-$(SuffixName)$(TestRun)'
              KeyVaultObjectId: '$(KeyVaultObjectId)'
              sqAdminPassword: '$(SonarDefaultAdminPassword)'
              KeyVault: '$(KeyVault)-$(TestRun)'
              ResourceGroup: '$(ResourceGroup)-$(SuffixName)$(TestRun)'
              HostingPlan: '$(HostingPlan)-$(TestRun)'
              Website: '$(Website)-$(TestRun)'
              SqlServer: '$(SqlServer)-$(TestRun)'
              SqlDb: '$(SqlDb)-$(TestRun)'
              SkuSize: '$(SkuSize)'
              SkuCapacity: '$(SkuCapacity)'
              SqlAdmin: '$(SqlAdmin)'
              SqlAdminPassword: '$(SqlAdminPassword)' 
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Cleanup Resources'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(AzureConnectionServiceName)'
              subscriptionId: '$(SubscriptionGuid)'
              action: 'DeleteRG'
              resourceGroupName: '$(ResourceGroup)-$(SuffixName)$(TestRun)'
              location: 'West Europe'

### PRODUCTION DEPLOYMENT ###
#############################

- stage: Production_Installation
  displayName: Production Installation
  dependsOn: Build
  condition: and(succeeded(), and(eq(variables['System.PullRequest.IsFork'], false),eq(variables['Build.SourceBranch'],'refs/heads/master')))
  jobs:
  - deployment: Deploy_ARM
    displayName: 'Deploy Infrastructure'    
    pool:
     vmImage: 'vs2017-win2016'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download AzureRessources
            artifact: AzureRessources
            patterns: '**/*.json'
          - download: current
            displayName: Download InstallScripts
            artifact: InstallScripts   
          - template: Pipeline/deployArm.yml
            parameters:
              AzureConnectionServiceName: '$(AzureConnectionServiceName)'
              SubscriptionGuid: '$(SubscriptionGuid)'
              KeyVaultResourceGroup: '$(ResourceGroupKeyVault)'
              KeyVaultObjectId: '$(KeyVaultObjectId)'
              sqAdminPassword: '$(SonarDefaultAdminPassword)'
              KeyVault: '$(KeyVault)'
              ResourceGroup: '$(ResourceGroup)'
              HostingPlan: '$(HostingPlan)'
              Website: '$(Website)'
              SqlServer: '$(SqlServer)'
              SqlDb: '$(SqlDb)'
              SkuSize: '$(SkuSize)'
              SkuCapacity: '$(SkuCapacity)'
              SqlAdmin: '$(SqlAdmin)'
              SqlAdminPassword: '$(SqlAdminPassword)'          
          - task: AzureRmWebAppDeployment@4
            displayName: "Deploy Installation Scripts"
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(AzureConnectionServiceName)'
              appType: 'webApp'
              WebAppName: '$(Website)'
              packageForLinux: '../InstallScripts/Deploy'
              enableCustomDeployment: true
              DeploymentType: 'webDeploy'
          - task: AzurePowerShell@4
            displayName: "Install SonarQube on WebApp"
            inputs:
              azureSubscription: '$(AzureConnectionServiceName)'
              ScriptType: 'FilePath'
              ScriptPath: '../InstallScripts/Deploy/RunPowerShellKudu.ps1'
              ScriptArguments: '-WebsiteName "$(Website)"'
              azurePowerShellVersion: 'LatestVersion'
              pwsh: true              
          - task: AzureRmWebAppDeployment@4
            displayName: "Deploy Run Scripts"
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(AzureConnectionServiceName)'
              appType: 'webApp'
              WebAppName: '$(Website)'
              packageForLinux: '../InstallScripts/Run'
              enableCustomDeployment: true
              DeploymentType: 'webDeploy'
          - task: AzurePowerShell@4
            displayName: "Configure SonarQube on WebApp"
            inputs:
              azureSubscription: '$(AzureConnectionServiceName)'
              ScriptType: 'FilePath'
              ScriptPath: '../InstallScripts/Deploy/ConfigureSonar.ps1'
              ScriptArguments: '-WebAppName "$(Website)" -AdminUser "$(SonarSecondaryAadAdmin)" -AadTenantId "$(TenantId)" -AadClientId "$(SonarAppId)" -AadClientSecret "$(SonarAppSecret)"'
              azurePowerShellVersion: 'LatestVersion'
              pwsh: true
          