# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'Visual Studio Enterprise: BizSpark(2b53247c-fb65-469e-a711-46e0c29d15a1)'
    subscriptionName: '2b53247c-fb65-469e-a711-46e0c29d15a1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Rp-SonarQubeAsAService'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM/sonar.azuredeploy.json'
    csmParametersFile: 'ARM/sonar.azuredeploy.parameters.json'
    overrideParameters: '-hostingPlanName "test" -webSiteName "test" -sqlserverName "test" -databaseName "test" -skuName "test" -skuCapacity 1 -sqlAdministratorLogin "test" -sqlAdministratorLoginPassword "test"'
    deploymentMode: 'Validation'